### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by methusalah** [methusalah/alchemist#1]
List of things to put in place for the first setup
- [x] Eclipse project into the github repository, java 8
- [x] jMonkey 3 dependancy (3.1 ?)
- [x] Event bus dep
- [x] Dependancy injection dep
- [x] Jackson dep
- [x] Tonegod dep
- [x] OpenRTS Geometry package (or dep?)
- [x] MVC pattern with jmonkey application (based on OpenRTS?)
- [x] Many app states : menu, in-game, map editor, other editors (entity, particles, scripts...) or many projets?
- [x] an Entity/Component framework
- [ ] Networking framework ?
- [x] a singleton Logger with different levels

**Comment by meltzow** [comment]
it's me, Mario !! (https://www.youtube.com/watch?v=ZhadLMDWcGA )

**Comment by methusalah** [comment]
@meltzow  Are we able to plug the openRTS network work on cosmovania right now? If not, let's close this and open another, dedicated to network for more long time goal

**Comment by meltzow** [comment]
I will check this, these days.
