### ISSUE TITLE
Liste des ressources non classée

### ISSUE THREAD

**Issue by draaxk** [methusalah/alchemist#11]
La liste des ressources n'a pas de classement intuitif (par exemple ordre alphabétique), et lors de la sauvegarde d'une entité, elle ajoute l'entité à la fin de la liste au lieu de mettre à jour l'entité du même nom dans la liste.

**Comment by methusalah** [comment]
done. Classement initial et reclassement en cas d'ajout.

De plus les blueprint sauvegardées ecrasent désormais l'encienne version

Reste à voir pour les organiser en dossier
