### ISSUE TITLE
Implement vertical chasing camera and controler

### ISSUE THREAD

**Issue by methusalah** [methusalah/alchemist#3]
the camera will look at (0, 0, -1) and wil be chasing the player ship (with latency? sloping?)

The first control will be : 
- directional key for displacement (zqsd/wasd, arrows and controller's stick)
- mouse for aiming (and controller's stick)

**Comment by meltzow** [comment]
for mapping the keys please use something like a abstraction for the keys. In SC2 its possible to define a new "keyboard layout" and there you can redefine your keys. No more <wasd> for moving, now its with the arrows. 
For example like this: Define a new class named "SimpleKeyboardMapper" which must implement a methode named "void inject(ImputManager inputManager). if I understand correct: http://wiki.jmonkeyengine.org/doku.php/jme3:advanced:input_handling ,so other users can override the SimpleKeyboardMapper" (using the DI).

**Comment by methusalah** [comment]
Camera is op. its is not controlled by player in gamemode (only in editor mode), but only folowing the ship, which is controlled by player.
